# frozen_string_literal: true

require 'matrix'

module PetriFlow
  module Matrix
    # CRUD-to-Event Mapping Matrix (M_ce)
    # Tracks which CRUD operations generate which event types
    class CrudEventMapping
      CRUD_OPERATIONS = %i[create update delete].freeze

      attr_reader :matrix, :crud_ops, :event_types

      def initialize
        @matrix = {}
        @crud_ops = CRUD_OPERATIONS.dup
        @event_types = []
      end

      # Record that a CRUD operation generates an event type
      def record_mapping(crud_op, event_type, count = 1)
        validate_crud_op!(crud_op)

        @event_types << event_type unless @event_types.include?(event_type)
        @matrix[crud_op] ||= Hash.new(0)
        @matrix[crud_op][event_type] += count
      end

      # Get mapping value for specific CRUD operation and event type
      def get(crud_op, event_type)
        @matrix.dig(crud_op, event_type) || 0
      end

      # Get total events generated by a CRUD operation
      def total_events_for(crud_op)
        @matrix[crud_op]&.values&.sum || 0
      end

      # Get all event types generated by a CRUD operation
      def events_for(crud_op)
        @matrix[crud_op]&.keys || []
      end

      # Convert to 2D array matrix
      def to_matrix
        rows = @crud_ops.map do |crud_op|
          @event_types.map { |event_type| get(crud_op, event_type) }
        end
        ::Matrix.rows(rows)
      end

      # Pretty print the mapping matrix
      def to_table
        header = ["CRUD \\ Event"] + @event_types.map(&:to_s)
        rows = @crud_ops.map do |crud_op|
          [crud_op.to_s.upcase] + @event_types.map { |et| get(crud_op, et) }
        end
        { header: header, rows: rows }
      end

      def to_s
        "CrudEventMapping(#{@crud_ops.size} operations, #{@event_types.size} event types)"
      end

      private

      def validate_crud_op!(crud_op)
        return if CRUD_OPERATIONS.include?(crud_op.to_sym)

        raise ArgumentError, "Invalid CRUD operation: #{crud_op}. Must be one of #{CRUD_OPERATIONS}"
      end
    end
  end
end
