require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "lib"
  t.libs << "test"
  t.test_files = FileList["test/**/*_test.rb"]
  t.verbose = true
end

task default: :test

desc "Run console with gem loaded"
task :console do
  require "irb"
  require "petri_flow"
  ARGV.clear
  IRB.start
end

desc "Generate example outputs"
task :examples do
  Dir.glob("examples/**/*.rb").each do |example|
    puts "Running #{example}..."
    load example
    puts ""
  end
end
