# frozen_string_literal: true
# Auto-generated by Lyra::Verification::WorkflowGenerator
# Generated at: 2026-10-05 05:52:34 UTC

# Event Sourcing Async Mode Workflow
# The event is stored; a job projects it into the table after commit
class EsAsyncModeWorkflow < PetriFlow::Workflow
  workflow_name "Event Sourcing Async Mode Workflow"

  places :idle, :command_built, :event_built, :event_applied, :event_stored, :response_returned, :job_enqueued, :projection_complete
  initial_place :idle
  terminal_places :response_returned, :projection_complete

  transition :intercept_write,
             from: :idle,
             to: :command_built,
             trigger: "WriteHooks: a Lyra::Command (a create first reserves its id); the row write is withheld"

  transition :build_event,
             from: :command_built,
             to: :event_built,
             trigger: "Lyra::CommandHandler.handle: create_events"

  transition :apply_event,
             from: :event_built,
             to: :event_applied,
             trigger: "aggregate.apply(event)"

  transition :store_event,
             from: :event_applied,
             to: :event_stored,
             trigger: "after_* callback lyra_finalize_event_source: Lyra.append_events"

  transition :async_fork,
             from: :event_stored,
             to: [:response_returned, :job_enqueued],
             trigger: "AsyncProjectionJob.perform_later, after commit"

  transition :project_row,
             from: :job_enqueued,
             to: :projection_complete,
             trigger: "AsyncProjectionJob writes the row from the event, under a per-stream lock"

end