# frozen_string_literal: true
# Auto-generated by Lyra::Verification::WorkflowGenerator
# Generated at: 2026-01-04 17:33:03 UTC
# Updated: Fork pattern for true async parallelism

# Event Sourcing Async Mode Workflow
# Full event sourcing with asynchronous (non-blocking) projection
#
# Uses Petri net FORK pattern to model true parallelism:
# After events are stored, a single fork transition places tokens in
# BOTH response_returned AND job_processing simultaneously.
# This correctly models async behavior where:
# 1. Response returns immediately to caller (non-blocking)
# 2. Background worker processes projection independently
class EsAsyncModeWorkflow < PetriFlow::Workflow
  workflow_name "Event Sourcing Async Mode Workflow"

  places :idle, :command_received, :aggregate_loading, :aggregate_loaded,
         :command_applying, :events_generated, :events_storing, :events_stored,
         :response_returned, :job_processing, :projecting_async, :projection_complete
  initial_place :idle
  terminal_places :response_returned, :projection_complete

  # Command processing flow (sequential)
  transition :receive_command,
             from: :idle,
             to: :command_received,
             trigger: "CommandHandler receives command"

  transition :load_aggregate,
             from: :command_received,
             to: :aggregate_loading,
             trigger: "Load aggregate from event stream"

  transition :aggregate_ready,
             from: :aggregate_loading,
             to: :aggregate_loaded,
             trigger: "Aggregate hydrated from events"

  transition :apply_command,
             from: :aggregate_loaded,
             to: :command_applying,
             trigger: "Aggregate.apply(command)"

  transition :generate_events,
             from: :command_applying,
             to: :events_generated,
             trigger: "Domain events created"

  transition :store_events,
             from: :events_generated,
             to: :events_storing,
             trigger: "EventStore.append_to_stream"

  transition :events_persisted,
             from: :events_storing,
             to: :events_stored,
             trigger: "Events committed to store"

  # FORK: Parallel split - one transition produces tokens in TWO places
  # This models the async behavior where both happen simultaneously:
  # - Response returns immediately to caller
  # - Background job is enqueued for processing
  transition :async_fork,
             from: :events_stored,
             to: [:response_returned, :job_processing],
             trigger: "Enqueue job & return response (parallel)"

  # Background projection flow (runs independently after fork)
  transition :project_async,
             from: :job_processing,
             to: :projecting_async,
             trigger: "ModelProjection.apply (async)"

  transition :async_complete,
             from: :projecting_async,
             to: :projection_complete,
             trigger: "Read model eventually consistent"

end