# frozen_string_literal: true
# Auto-generated by Lyra::Verification::WorkflowGenerator
# Generated at: 2026-01-04 17:33:03 UTC

# Event Sourcing Sync Mode Workflow
# Full event sourcing with synchronous (blocking) projection
class EsSyncModeWorkflow < PetriFlow::Workflow
  workflow_name "Event Sourcing Sync Mode Workflow"

  places :idle, :command_received, :aggregate_loading, :aggregate_loaded, :command_applying, :events_generated, :events_storing, :events_stored, :projecting_sync, :projection_complete, :completed
  initial_place :idle
  terminal_places :completed

  transition :receive_command,
             from: :idle,
             to: :command_received,
             trigger: "CommandHandler receives command"

  transition :load_aggregate,
             from: :command_received,
             to: :aggregate_loading,
             trigger: "Load aggregate from event stream"

  transition :aggregate_ready,
             from: :aggregate_loading,
             to: :aggregate_loaded,
             trigger: "Aggregate hydrated from events"

  transition :apply_command,
             from: :aggregate_loaded,
             to: :command_applying,
             trigger: "Aggregate.apply(command)"

  transition :generate_events,
             from: :command_applying,
             to: :events_generated,
             trigger: "Domain events created"

  transition :store_events,
             from: :events_generated,
             to: :events_storing,
             trigger: "EventStore.append_to_stream"

  transition :events_persisted,
             from: :events_storing,
             to: :events_stored,
             trigger: "Events committed to store"

  transition :project_sync,
             from: :events_stored,
             to: :projecting_sync,
             trigger: "ModelProjection.apply (synchronous)"

  transition :sync_complete,
             from: :projecting_sync,
             to: :projection_complete,
             trigger: "Read model updated"

  transition :finalize,
             from: :projection_complete,
             to: :completed,
             trigger: "Response returned to caller"

end