# frozen_string_literal: true
# Auto-generated by Lyra::Verification::WorkflowGenerator
# Generated at: 2026-10-05 05:52:34 UTC

# Event Sourcing Sync Mode Workflow
# The event is stored, then projected into the table in the same transaction
class EsSyncModeWorkflow < PetriFlow::Workflow
  workflow_name "Event Sourcing Sync Mode Workflow"

  places :idle, :command_built, :event_built, :event_applied, :event_stored, :completed
  initial_place :idle
  terminal_places :completed

  transition :intercept_write,
             from: :idle,
             to: :command_built,
             trigger: "WriteHooks: a Lyra::Command (a create first reserves its id); the row write is withheld"

  transition :build_event,
             from: :command_built,
             to: :event_built,
             trigger: "Lyra::CommandHandler.handle: create_events"

  transition :apply_event,
             from: :event_built,
             to: :event_applied,
             trigger: "aggregate.apply(event)"

  transition :store_event,
             from: :event_applied,
             to: :event_stored,
             trigger: "after_* callback lyra_finalize_event_source: Lyra.append_events"

  transition :project_row,
             from: :event_stored,
             to: :completed,
             trigger: "synchronous projection writes the row from the event"

end