# frozen_string_literal: true
# Auto-generated by Lyra::Verification::WorkflowGenerator
# Generated at: 2026-10-05 05:52:34 UTC

# Hijack Mode Workflow
# The event is built and stored before the row, which is written from it
class HijackModeWorkflow < PetriFlow::Workflow
  workflow_name "Hijack Mode Workflow"

  places :idle, :command_built, :event_built, :event_applied, :event_stored, :completed
  initial_place :idle
  terminal_places :completed

  transition :intercept_write,
             from: :idle,
             to: :command_built,
             trigger: "WriteHooks, after the model's before_* callbacks: a Lyra::Command (a create first reserves its id)"

  transition :build_event,
             from: :command_built,
             to: :event_built,
             trigger: "Lyra::CommandHandler.handle: create_events"

  transition :apply_event,
             from: :event_built,
             to: :event_applied,
             trigger: "aggregate.apply(event): the event joins the aggregate's pending events"

  transition :store_event,
             from: :event_applied,
             to: :event_stored,
             trigger: "aggregate.store: Lyra.append_events"

  transition :write_row,
             from: :event_stored,
             to: :completed,
             trigger: "ActiveRecord writes the row with the event's attributes"

end