# frozen_string_literal: true
# Auto-generated by Lyra::Verification::WorkflowGenerator
# Generated at: 2026-01-04 17:33:03 UTC

# Hijack Mode Workflow
# Intercepts CRUD operations and converts to event sourcing
class HijackModeWorkflow < PetriFlow::Workflow
  workflow_name "Hijack Mode Workflow"

  places :idle, :crud_intercepted, :command_created, :command_validating, :command_valid, :event_created, :event_stored, :projecting, :completed
  initial_place :idle
  terminal_places :completed

  transition :intercept_crud,
             from: :idle,
             to: :crud_intercepted,
             trigger: "before_* callback intercepts operation"

  transition :create_command,
             from: :crud_intercepted,
             to: :command_created,
             trigger: "Convert CRUD to Lyra::Command"

  transition :validate_command,
             from: :command_created,
             to: :command_validating,
             trigger: "CommandHandler.validate"

  transition :command_passes,
             from: :command_validating,
             to: :command_valid,
             trigger: "Validation passes"

  transition :emit_event,
             from: :command_valid,
             to: :event_created,
             trigger: "CommandHandler.execute creates event"

  transition :store_event,
             from: :event_created,
             to: :event_stored,
             trigger: "RailsEventStore.publish"

  transition :project_state,
             from: :event_stored,
             to: :projecting,
             trigger: "Projection.apply(event)"

  transition :projection_complete,
             from: :projecting,
             to: :completed,
             trigger: "Model state updated from event"

end