# frozen_string_literal: true
# Auto-generated by Lyra::Verification::WorkflowGenerator
# Generated at: 2026-01-04 17:33:03 UTC

# CRUD Entity Lifecycle (Generated)
class LifecycleWorkflow < PetriFlow::Workflow
  workflow_name "CRUD Entity Lifecycle (Generated)"

  places :nonexistent, :created, :persisted, :updated, :destroyed, :deleted
  initial_place :nonexistent
  terminal_places :deleted

  transition :create,
             from: :nonexistent,
             to: :created,
             trigger: "after_create"

  transition :emit_created_event,
             from: :created,
             to: :persisted,
             trigger: "publish Created event"

  transition :update,
             from: :persisted,
             to: :updated,
             trigger: "after_update"

  transition :emit_updated_event,
             from: :updated,
             to: :persisted,
             trigger: "publish Updated event"

  transition :destroy,
             from: :persisted,
             to: :destroyed,
             trigger: "after_destroy"

  transition :emit_destroyed_event,
             from: :destroyed,
             to: :deleted,
             trigger: "publish Destroyed event"

end