# frozen_string_literal: true
# Auto-generated by Lyra::Verification::WorkflowGenerator
# Generated at: 2026-10-05 05:52:34 UTC

# Monitor Mode Workflow
# The row is written as usual; the event follows in the same transaction
class MonitorModeWorkflow < PetriFlow::Workflow
  workflow_name "Monitor Mode Workflow"

  places :idle, :row_written, :event_built, :completed
  initial_place :idle
  terminal_places :completed

  transition :write_row,
             from: :idle,
             to: :row_written,
             trigger: "ActiveRecord writes the row"

  transition :build_event,
             from: :row_written,
             to: :event_built,
             trigger: "after_* callback: CrudInterceptor#publish_event builds it (Lyra::DomainEvents.build)"

  transition :append_event,
             from: :event_built,
             to: :completed,
             trigger: "Lyra.append_events, in a savepoint of the same transaction"

end