# frozen_string_literal: true
# Auto-generated by Lyra::Verification::WorkflowGenerator
# Generated at: 2026-01-04 17:33:03 UTC

# Monitor Mode Workflow
# Passively observes CRUD operations without modification
class MonitorModeWorkflow < PetriFlow::Workflow
  workflow_name "Monitor Mode Workflow"

  places :idle, :crud_executing, :crud_completed, :event_building, :event_publishing, :completed
  initial_place :idle
  terminal_places :completed

  transition :receive_crud,
             from: :idle,
             to: :crud_executing,
             trigger: "ActiveRecord callback triggered"

  transition :crud_success,
             from: :crud_executing,
             to: :crud_completed,
             trigger: "CRUD operation completes successfully"

  transition :build_event,
             from: :crud_completed,
             to: :event_building,
             trigger: "Extract changes from model"

  transition :publish_event,
             from: :event_building,
             to: :event_publishing,
             trigger: "Lyra::Event.publish"

  transition :store_event,
             from: :event_publishing,
             to: :completed,
             trigger: "RailsEventStore.publish"

end